version: '3.8'

services:
  node1:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node1
    environment:
      - THIS_NODE=node1
    ports:
      - "5001:5000"
    networks:
      - gossipnet

  node2:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node2
    environment:
      - THIS_NODE=node2
    ports:
      - "5002:5000"
    networks:
      - gossipnet

  node3:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node3
    environment:
      - THIS_NODE=node3
    ports:
      - "5003:5000"
    networks:
      - gossipnet

  node4:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node4
    environment:
      - THIS_NODE=node4
    ports:
      - "5004:5000"
    networks:
      - gossipnet

  node5:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node5
    environment:
      - THIS_NODE=node5
    ports:
      - "5005:5000"
    networks:
      - gossipnet

  log-viewer:
    build:
      context: .
      dockerfile: docker/log-viewer.Dockerfile
    container_name: log-viewer
    volumes:
      - ./frontend/static:/app/static
    networks:
      - gossipnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - log-viewer
    networks:
      - gossipnet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
    networks:
      - gossipnet

networks:
  gossipnet:
    driver: bridge