version: '3.8'

services:
  node1:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node1
    environment:
      - THIS_NODE=node1
    networks:
      - gossipnet

  node2:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node2
    environment:
      - THIS_NODE=node2
    networks:
      - gossipnet

  node3:
    build:
      context: ./backend
      dockerfile: ../docker/node.Dockerfile
    container_name: node3
    environment:
      - THIS_NODE=node3
    networks:
      - gossipnet

  log-viewer:
    build:
      context: .
      dockerfile: docker/log-viewer.Dockerfile
    container_name: log-viewer
    volumes:
      - ./frontend/static:/app/static
    networks:
      - gossipnet

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node1
      - node2
      - node3
      - log-viewer
    networks:
      - gossipnet

networks:
  gossipnet:
    driver: bridge