name: Gossip Protocol CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements-test.txt

    - name: Build and start Docker containers
      run: |
        docker compose up -d --build

    - name: Wait for services to be ready
      run: |
        sleep 50

    - name: Run tests
      env:
        NODE_BASE_URL: http://localhost
        NODE_PORTS: 5001,5002,5003,5004,5005
        PYTHONPATH: ${{ github.workspace }}/backend
      run: |
        cd backend
        python -m pytest tests/test_gossip.py -v --tb=short

    - name: Check test results
      if: always()
      run: |
        echo "=== Container Status ==="
        docker compose ps
        echo "=== Container Logs ==="
        docker compose logs

    - name: Cleanup
      if: always()
      run: |
        docker compose down -v